git:
  remoteRepository: "${REPOSITORY}"
  localRepositoryRoot: "${REPOSITORY_LOCAL_CACHE}"
  privateKeyFile: "${PRIVATE_KEY_FILE}"
  ignoreInsecureHosts: true
rabbitmq:
  host: "${RABBITMQ_HOST}"
  port: "${RABBITMQ_PORT}"
  vhostPrefix: "${RABBITMQ_VHOST_PREFIX}"
  user: "${RABBITMQ_USER}"
  password: "${RABBITMQ_PASS}"

kubernetes:
  useCustomConfig: false
  namespacePrefix: "${K8S_NAMESPACE_PREFIX}"

  commonConfigMap: "${K8S_COMMON_CONFIG}"
  secretNames:
    - "chart-secrets"
    - "git-chart-creds"
    - "th2-core"
    - "th2-solution"
    - "cassandra"
    - "rabbitmq"
