git:
  remoteRepository: "git@gitlab.exactpro.com:giorgi.mania/scheme-files.git"
  localRepositoryRoot: "/home/exp.exactpro.com/giorgi.mania/.sche_be"
  privateKeyFile: "/home/exp.exactpro.com/giorgi.mania/.ssh/scheme_designer_backend"


