git:
  remoteRepository: "${REPOSITORY}"
  localRepositoryRoot: "${REPOSITORY_CACHE}"
  privateKey: "${PRIVATE_KEY}"
  ignoreInsecureHosts: true
kubernetes:
  useCustomConfig: false
  ignoreInsecureHosts: true

  secretNames:
    - "th2-core"
    - "th2-solution"
    - "rabbitmq-token-7b6xx"
    - "cassandra"
    - "rabbitmq"
