git:
  remoteRepository: "${REPOSITORY}"
  localRepositoryRoot: "${REPOSITORY_LOCAL_CACHE}"
  privateKeyFile: "${PRIVATE_KEY_FILE}"
  ignoreInsecureHosts: true
kubernetes:
  useCustomConfig: false

  secretNames:
    - "chart-secrets"
    - "git-chart-creds"
    - "th2-core"
    - "th2-solution"
    - "cassandra"
    - "rabbitmq"
